# Generated by Django 3.0.5 on 2020-06-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReactionTimeAPI', '0005_auto_20200603_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
