# Generated by Django 3.0.5 on 2020-06-04 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ReactionTimeAPI', '0007_experiment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentresult',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
