# Generated by Django 3.0.5 on 2020-06-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReactionTimeAPI', '0009_experiment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('general', 'General'), ('simple', 'Simple'), ('discrimination', 'Discrimination'), ('choice', 'Choice'), ('recognition', 'Recognition')], max_length=20)),
                ('minTimeout', models.IntegerField(default=2000)),
                ('maxTimeout', models.IntegerField(default=4000)),
                ('tries', models.IntegerField(default=5)),
            ],
        ),
    ]
