# Generated by Django 3.0.5 on 2020-06-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReactionTimeAPI', '0010_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('simple', 'Simple'), ('discrimination', 'Discrimination'), ('choice', 'Choice'), ('recognition', 'Recognition')], max_length=20, unique=True),
        ),
    ]
